data<-read.csv("household_power_consumption.txt",sep=";",stringsAsFactors = FALSE)
d<-rbind(data[data$Date=="1/2/2007",] ,data[data$Date=="2/2/2007",])
png(filename = "plot4.png",width = 480, height = 480) 
par(mfrow=c(2,2))
plot(d$Global_active_power,type="l",ylab="Global active power (kilowatts)",xlab="",xaxt = "n")
axis(1,xaxp=c(0,2800,2),at=c(0,1400,2800),labels=c("Thu","Fri","Sat"))
plot(d$Voltage,type="l",ylab="Voltage",xlab="datetime",xaxt = "n")
axis(1,xaxp=c(0,2800,2),at=c(0,1400,2800),labels=c("Thu","Fri","Sat"))
plot(d$Sub_metering_1,xlab="",xaxt = "n",type="l",ylab="Energy sub metering")
points(d$Sub_metering_2,type="l",col="red")
points(d$Sub_metering_3,type="l",col="blue")
axis(1,xaxp=c(0,2800,2),at=c(0,1400,2800),labels=c("Thu","Fri","Sat"))
legend("topright",cex=0.2,col=c("black","red", "blue"), lty=c(1,1,1),legend=c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"))
plot(d$Global_reactive_power,type="l",ylab="Global_reactive_power",xlab="datetime",xaxt = "n")
axis(1,xaxp=c(0,2800,2),at=c(0,1400,2800),labels=c("Thu","Fri","Sat"))
dev.off()
